//
//  ManufacturerWorkerTests.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CarDealerApp
import XCTest

class ManufacturerWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ManufacturerWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupManufacturerWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupManufacturerWorker() {
        sut = ManufacturerWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
