//
//  CarModelsPresenter.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CarModelsPresentationLogic {
    func presentView(response: CarModels.CarModel.Response)
    func presentSelection(response: CarModels.Alert.Response)
}

class CarModelsPresenter: CarModelsPresentationLogic {
    weak var viewController: CarModelsDisplayLogic?


    func presentView(response: CarModels.CarModel.Response) {
        let models = response.carDealerResponse.wkda.map {  $0.value }

        let viewModel = CarModels.CarModel.ViewModel(
            models: models,
            indexPathsToReload: response.indexPathsToReload.count == 0 ?
                nil : response.indexPathsToReload,
            loadingRowCount: response.addLoadingRow ? 1 : 0,
            title: response.title.isEmpty ? nil : response.title
        )

        viewController?.displayView(viewModel: viewModel)
    }

    func presentSelection(response: CarModels.Alert.Response) {
        let viewModel = CarModels.Alert.ViewModel(
            title: response.title,
            message: response.message
        )
        viewController?.displayAlert(viewModel: viewModel)
    }
}
