//
//  CarModelsModels.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CarModels {
    // MARK: Use cases

    enum CarModel {
        struct Request {
        }
        struct Response {
            var carDealerResponse: CarDealerResponse
            var indexPathsToReload: [IndexPath]
            var addLoadingRow: Bool
            var title: String 
        }
        struct ViewModel {
            var models: [String]
            var indexPathsToReload: [IndexPath]?
            var loadingRowCount: Int
            var title: String?
        }
    }
}
