//
//  ManufacturerModels.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Manufacturer {
    // MARK: Use cases

    enum Manufacturer {
        struct Request {
            var page: String
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
