//
//  ManufacturerPresenter.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ManufacturerPresentationLogic {
    func presentLoading()
    func dismissLoading()
    func presentView(response: Manufacturer.Manufacturer.Response)
    func presentModels()
}

class ManufacturerPresenter: ManufacturerPresentationLogic {
    weak var viewController: ManufacturerDisplayLogic?

    func presentLoading() {
        viewController?.displayLoading()
    }

    func dismissLoading() {
        viewController?.dismissLoading()
    }

    func presentView(response: Manufacturer.Manufacturer.Response) {
        let manufacturers = response.carDealerResponse.wkda.map {
            ManufacturerModel(id: $0.key, name: $0.value)
        }

        let viewModel = Manufacturer.Manufacturer.ViewModel(
            manufacturers: manufacturers,
            indexPathsToReload: response.indexPathsToReload.count == 0 ?
            nil : response.indexPathsToReload,
            loadingRowCount: response.addLoadingRow ? 1 : 0
        )

        viewController?.displayView(viewModel: viewModel)
    }

    func presentModels() {
        viewController?.displayModels()
    }
}
