//
//  ManufacturerPresenter.swift
//  CarDealerApp
//
//  Created by Nisum on 11/16/19.
//  Copyright (c) 2019 Orlando Arzola. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ManufacturerPresentationLogic {
    func presentLoading()
    func dismissLoading()
    func presentView(response: Manufacturer.Manufacturer.Response)
}

class ManufacturerPresenter: ManufacturerPresentationLogic {
    weak var viewController: ManufacturerDisplayLogic?

    func presentLoading() {
        viewController?.displayLoading()
    }

    func dismissLoading() {
        viewController?.dismissLoading()
    }

    func presentView(response: Manufacturer.Manufacturer.Response) {
        
    }
}
